project_name: "test1"
subject_code: "YAB"
freesurfer_directory: "~/Downloads/iELVis_Localization/YAS/"
ct_aligned_t1: "~/Downloads/iELVis_Localization/YAS_CT_aligned1.nii"
symlink: no
overwrite: yes
fs_within_rave: no
localize: yes
localize_params:
  surfaces:
    - pial
    - white
  use_suma_141: yes
shiny_options:
  launch.browser: yes
  host: "127.0.0.1"
  port: NA
