changes: []
electrode_group:
  '1':
    name: OOB
    electrodes: 1-12
  '2':
    name: Grid
    electrodes: 13-63
  '3':
    name: Bad
    electrodes: '64'
  '4':
    name: B1
    electrodes: 65-84
project_name: test3
reference_name: _unsaved
subject_code: YAB
