baseline:
- - -1
  - -0.2
baseline_method: decibel
electrodes: '14'
epoch: default
intervals:
- - -1.0
  - 2.0
project_name: demo
reference: default
save_pipeline: yes
subject_code: DemoSubject
type: power
