changes:
- group_name: Default
  electrodes: 1-84
  reference_type: Common Average Reference
  reference_signal: ref_13-63,65-84
electrode_group:
  '1':
    name: Default
    electrodes: 1-84
project_name: devel
reference_name: _unsaved
subject_code: YAB
