changes:
- group_name: Default
  electrodes: 1-14
  reference_type: Common Average Reference
  reference_signal: ref_1-13
electrode_group:
  '1':
    name: Default
    electrodes: 1-14
project_name: test2
reference_name: _unsaved
subject_code: KC
