changes:
- group_name: G1
  electrodes: 13-15
  reference_type: Common Average Reference
  reference_signal: ref_15-24
electrode_group:
  '1':
    name: G1
    electrodes: 13-15
  '2':
    name: G2
    electrodes: 16-25
project_name: test3
reference_name: _unsaved
subject_code: YAB
