changes:
- group_name: G2
  electrodes: 17-24
  reference_type: Bipolar Reference
  reference_signal:
  - ref_18
  - ref_19
  - ref_20
  - ref_21
  - ref_22
  - ref_23
  - ref_24
  - ''
electrode_group:
  '1':
    name: G1
    electrodes: 15-16
  '2':
    name: G2
    electrodes: 17-24
project_name: test3
reference_name: _unsaved
subject_code: YAB
