changes:
- group_name: Nolabel
  electrodes: 1-233
  reference_type: Common Average Reference
  reference_signal: ref_1-200
electrode_group:
  '1':
    name: Nolabel
    electrodes: 1-233
project_name: test
reference_name: _unsaved
subject_code: PAV004
