changes:
- group_name: Default
  electrodes: 14-15
  reference_type: Common Average Reference
  reference_signal: ref_14-15
electrode_group:
  '1':
    name: Default
    electrodes: 14-15
project_name: test
reference_name: '[Blank profile]'
subject_code: YAB
