changes:
- group_name: LA
  electrodes: 13-21
  reference_type: Bipolar Reference
  reference_signal:
  - ref_14
  - ref_15
  - ref_16
  - ref_17
  - ref_18
  - ref_19
  - ref_20
  - ref_21
  - ref_22
- group_name: LB
  electrodes: 25-33
  reference_type: Bipolar Reference
  reference_signal:
  - ref_26
  - ref_27
  - ref_28
  - ref_29
  - ref_30
  - ref_31
  - ref_32
  - ref_33
  - noref
- group_name: LI
  electrodes: 4-6
  reference_type: Bipolar Reference
  reference_signal:
  - ref_5
  - ref_6
  - noref
electrode_group:
  '1':
    name: LA
    electrodes: 13-21
  '2':
    name: Bipolar-last-electrode
    electrodes: '7,22,34,44,58,68,81,93,104'
  '3':
    name: LB
    electrodes: 25-33
  '4':
    name: LI
    electrodes: 4-6
  '5':
    name: OOB-LA
    electrodes: 23-24
  '6':
    name: OOB-LB
    electrodes: 35-36
  '7':
    name: OOB-LI
    electrodes: 1-3,8-12
  '8':
    name: OOB-RA
    electrodes: 59-60
  '9':
    name: OOB-RB
    electrodes: 69-72
  '10':
    name: OOB-RC
    electrodes: 82-84
  '11':
    name: OOB-RD
    electrodes: 94-96
  '12':
    name: OOB-RI
    electrodes: 45-48
  '13':
    name: OOB-RQ
    electrodes: 105-108
  '14':
    name: OTHERS
    electrodes: 109-116
  '15':
    name: RA
    electrodes: 49-57
  '16':
    name: RB
    electrodes: 61-67
  '17':
    name: RC
    electrodes: 73-80
  '18':
    name: RD
    electrodes: 85-92
  '19':
    name: RI
    electrodes: 37-43
  '20':
    name: RQ
    electrodes: 97-103
project_name: test
reference_name: _unsaved
subject_code: PAV006
