changes:
- group_name: Nolabel
  electrodes: 1-233
  reference_type: Bipolar Reference
  reference_signal:
  - ref_2
  - ref_3
  - ref_4
  - ref_5
  - ref_6
  - ref_7
  - ref_8
  - ref_9
  - ref_10
  - ref_11
  - ref_12
  - ref_13
  - ref_14
  - ref_15
  - ref_16
  - ref_17
  - ref_18
  - ref_19
  - ref_20
  - ref_21
  - ref_22
  - ref_23
  - ref_24
  - ref_25
  - ref_26
  - ref_27
  - ref_28
  - ref_29
  - ref_30
  - ref_31
  - ref_32
  - ref_33
  - ref_34
  - ref_35
  - ref_36
  - ref_37
  - ref_38
  - ref_39
  - ref_40
  - ref_41
  - ref_42
  - ref_43
  - ref_44
  - ref_45
  - ref_46
  - ref_47
  - ref_48
  - ref_49
  - ref_50
  - ref_51
  - ref_52
  - ref_53
  - ref_54
  - ref_55
  - ref_56
  - ref_57
  - ref_58
  - ref_59
  - ref_60
  - ref_61
  - ref_62
  - ref_63
  - ref_64
  - ref_65
  - ref_66
  - ref_67
  - ref_68
  - ref_69
  - ref_70
  - ref_71
  - ref_72
  - ref_73
  - ref_74
  - ref_75
  - ref_76
  - ref_77
  - ref_78
  - ref_79
  - ref_80
  - ref_81
  - ref_82
  - ref_83
  - ref_84
  - ref_85
  - ref_86
  - ref_87
  - ref_88
  - ref_89
  - ref_90
  - ref_91
  - ref_92
  - ref_93
  - ref_94
  - ref_95
  - ref_96
  - ref_97
  - ref_98
  - ref_99
  - ref_100
  - ref_101
  - ref_102
  - ref_103
  - ref_104
  - ref_105
  - ref_106
  - ref_107
  - ref_108
  - ref_109
  - ref_110
  - ref_111
  - ref_112
  - ref_113
  - ref_114
  - ref_115
  - ref_116
  - ref_117
  - ref_118
  - ref_119
  - ref_120
  - ref_121
  - ref_122
  - ref_123
  - ref_124
  - ref_125
  - ref_126
  - ref_127
  - ref_128
  - ref_129
  - ref_130
  - ref_131
  - ref_132
  - ref_133
  - ref_134
  - ref_135
  - ref_136
  - ref_137
  - ref_138
  - ref_139
  - ref_140
  - ref_141
  - ref_142
  - ref_143
  - ref_144
  - ref_145
  - ref_146
  - ref_147
  - ref_148
  - ref_149
  - ref_150
  - ref_151
  - ref_152
  - ref_153
  - ref_154
  - ref_155
  - ref_156
  - ref_157
  - ref_158
  - ref_159
  - ref_160
  - ref_161
  - ref_162
  - ref_163
  - ref_164
  - ref_165
  - ref_166
  - ref_167
  - ref_168
  - ref_169
  - ref_170
  - ref_171
  - ref_172
  - ref_173
  - ref_174
  - ref_175
  - ref_176
  - ref_177
  - ref_178
  - ref_179
  - ref_180
  - ref_181
  - ref_182
  - ref_183
  - ref_184
  - ref_185
  - ref_186
  - ref_187
  - ref_188
  - ref_189
  - ref_190
  - ref_191
  - ref_192
  - ref_193
  - ref_194
  - ref_195
  - ref_196
  - ref_197
  - ref_198
  - ref_199
  - ref_200
  - ref_201
  - ref_202
  - ref_203
  - ref_204
  - ref_205
  - ref_206
  - ref_207
  - ref_208
  - ref_209
  - ref_210
  - ref_211
  - ref_212
  - ref_213
  - ref_214
  - ref_215
  - ref_216
  - ref_217
  - ref_218
  - ref_219
  - ref_220
  - ref_221
  - ref_222
  - ref_223
  - ref_224
  - ref_225
  - ref_226
  - ref_227
  - ref_228
  - ref_229
  - ref_230
  - ref_231
  - ref_232
  - ref_233
  - noref
electrode_group:
  '1':
    name: Nolabel
    electrodes: 1-233
project_name: test
reference_name: _unsaved
subject_code: PAV004
