controllers: []
data_source: Uploads
data_source_pipeline: power_explorer/power_explorer-22_09_03-22_54_46
data_source_pipeline_target: omnibus_results
data_source_project: demo
main_camera: []
project_name: demo
shiny_outputId: custom_3d_viewer-viewer_ready
subject_code: YAB
surface_types: ~
template_ok: no
uploaded_source: YAB_demo_export-20210525-072121.fst
