electrode_category_selector: freesurferlabel
unit_of_analysis: '% Change Power'
analysis_electrodes: 13-16,24
trial_starts: -1
epoch_name: auditory_onset
reference_name: default
loaded_electrodes: 13-16,24
subject_code: DemoSubject
project_name: demo
trial_ends: 2
condition_groups:
- group_name: All Conditions
  group_conditions:
  - AdriveVlast
  - AknownVmeant
  - AlastVknown
  - AmeantVdrive
  - drive_a
  - drive_av
  - drive_v
  - known_a
  - known_av
  - known_v
  - last_a
  - last_av
  - last_v
  - meant_a
  - meant_av
  - meant_v
  - press_AV
