project_name: "automated"
subject_code: "PAV004__block002"
load_electrodes: "1:20,110,128"
reference_name: ~
block: block002
requested_electrode: 128
baseline_method: "Block-Median"
baseline_unit: "Decibel"
