analysis_block: block006
analysis_electrodes: 1-116
analysis_time:
- 261.4143719
- 263.7767911
block:
- block006
- block007
- block008
filter_bandpass:
  enabled: no
filter_notch:
  enabled: no
hide_electrodes: ''
highlight_electrodes: ''
loaded_electrodes: 1-116
project_name: devel
pwelch_frequency_limit:
- 0
- 300
pwelch_params:
  window_size: 4000
  noverlap: 2000.0
subject_code: PAV006
vertical_spacing: ~
