analysis_block: block006
analysis_electrodes: 1-116
block:
- block006
- block007
- block008
filter_bandpass:
  enabled: yes
  order: 665
  range:
  - 7
  - 12
filter_notch:
  enabled: no
loaded_electrodes: 1-116
project_name: devel
pwelch_params:
  window_size: 4000
  noverlap: 2000.0
subject_code: PAV006
