analysis_electrodes: '14'
analysis_electrodes__category: Electrode
baseline_method: Block-Median
baseline_unit: Decibel
block: 008
loaded_electrodes: 13-16,24
project_name: demo
reference_name: noref
subject_code: DemoSubject
