diagnostic_plot_params:
  path: /var/folders/d7/xvwd68xd12bfpx38nb32w6b80000gp/T//RtmpCReNDV/filea4755b204c13.pdf
  window_length: 4000
  max_frequency: 300
  histogram_bins: 60
  background: '#ffffff'
  foreground: '#212529'
  font_size: 2.0
  quiet: no
notch_filter_lowerbound:
- 59.0
- 118.0
- 178.0
notch_filter_upperbound:
- 61.0
- 122.0
- 182.0
project_name: test
subject_code: PAV005
