dcm2niix_path: /usr/local/bin/dcm2niix
dryrun: no
freesurfer_path: /data/R/cache_dir/freesurfer
fsl_path: /data/R/cache_dir/fsl
params:
  nii_t1: ''
  nii_ct: ''
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  freesurfer:
    steps: -all
    fresh_start: no
params_dcm2niix: ~
path_ct: Guerrero_Evangelina_Cortez/CTBRAINWITHOUTCONTRAST
path_mri: Guerrero_Evangelina_Cortez/mri
project_name: devel
skip_coregistration: no
skip_recon: no
subject_code: YAB
