dcm2niix_path: /opt/homebrew/bin/dcm2niix
dryrun: yes
freesurfer_path: ''
fsl_path: ''
params:
  nii_t1: ''
  nii_ct: ''
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  freesurfer:
    steps: -all
    fresh_start: no
params_dcm2niix: ~
path_ct: Harris_Ralph_Emanuel_CT
path_mri: Harris_Ralph_Emanuel_MR
project_name: devel
skip_coregistration: no
skip_recon: no
subject_code: YAB
