dcm2niix_path: /opt/homebrew/Cellar/dcm2niix/1.0.20211006/bin/dcm2niix
dryrun: yes
freesurfer_path: ''
fsl_path: ''
params:
  nii_t1: ''
  nii_ct: ''
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  freesurfer:
    steps: -all
    fresh_start: no
params_dcm2niix: ~
path_ct: IMG/IMG/YCQ_CT.nii
path_mri: IMG/IMG/YCQ_MRI.nii
project_name: test3
skip_coregistration: no
skip_recon: no
subject_code: YCQ
