afni_path: /Users/dipterix/abin
dcm2niix_path: /opt/homebrew/Cellar/dcm2niix/1.0.20220720/bin/dcm2niix
freesurfer_path: /Applications/freesurfer/7.3.2
fsl_path: /usr/local/fsl
params:
  nii_t1: ''
  nii_ct: ''
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  freesurfer:
    flag: -autorecon1
    fresh_start: no
path_ct: 008
path_mri: 008
project_name: demo
skip_coregistration: no
skip_recon: no
subject_code: DemoSubject
