dcm2niix_path: /opt/homebrew/Cellar/dcm2niix/1.0.20211006/bin/dcm2niix
dryrun: yes
freesurfer_path: /Applications/freesurfer/7.2.0
fsl_path: /usr/local/fsl
params:
  nii_t1: ''
  nii_ct: ''
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  freesurfer:
    steps: -all
    fresh_start: no
params_dcm2niix: ~
path_ct: IMG/CT-MRI
path_mri: IMG/CT-MRI
project_name: devel
skip_coregistration: no
skip_recon: no
subject_code: YDS
