dcm2niix_path: /usr/local/bin/dcm2niix
dryrun: no
freesurfer_path: /data/R/cache_dir/freesurfer
fsl_path: /data/R/cache_dir/fsl
params:
  nii_t1: mri_t1_mprage_cc_20120418131207_2.nii
  nii_ct: CTBRAINWITHOUTCONTRAST_01_Stealth_Brain_Head_20120424163053_3.nii
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  freesurfer:
    steps: -all
    fresh_start: no
params_dcm2niix: ~
path_ct: Guerrero_Evangelina_Cortez/CTBRAINWITHOUTCONTRAST
path_mri: Guerrero_Evangelina_Cortez/mri
project_name: devel
skip_coregistration: no
skip_recon: yes
subject_code: YAB
