skip_coregistration: no
path_ct: POST_IMPLANT_CT/DICOM
dcm2niix_path: /opt/homebrew/Cellar/dcm2niix/1.0.20220720/bin/dcm2niix
params:
  nii_t1: MRI_RAW.nii
  nii_ct: POST_IMPLANT_CT_1_STEALTH_20220824232445_2.nii
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  freesurfer:
    flag: -autorecon1
    fresh_start: no
  niftyreg:
    reference: MRI_RAW.nii
    reg_type: rigid
    interp: trilinear
  ants:
    reference: MRI_RAW.nii
    reg_type: Rigid
    aff_metric: mattes
    syn_metric: mattes
  flirt:
    reference: MRI_RAW.nii
    dof: 6
    cost: mutualinfo
    search: 90
    searchcost: mutualinfo
  nipy:
    reference: MRI_RAW.nii
    clean_source: yes
    inverse_target: yes
    precenter_source: yes
    reg_type: rigid
    similarity: crl1
    interp: pv
    optimizer: powell
  afni:
    reference: MRI_RAW.nii
afni_path: /Users/dipterix/abin
skip_recon: no
path_mri: pre-MRI/DICOM_SAG_MPRAGE_20220728090416_13.nii
project_name: devel
freesurfer_path: /Applications/freesurfer/7.3.2
fsl_path: /usr/local/fsl
subject_code: PAV006
