dcm2niix_path: /usr/bin/dcm2niix
dryrun: yes
freesurfer_path: /data/software/freesurfer
fsl_path: ''
params:
  nii_t1: ''
  nii_ct: ''
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  freesurfer:
    steps: -all
    fresh_start: no
params_dcm2niix: ~
path_ct: IMG/YCQ_CT.nii
path_mri: IMG/YCQ_MRI.nii
project_name: devel
skip_coregistration: no
skip_recon: no
subject_code: YCQ
