subject_code: YAH
fsl_path: /usr/local/fsl
freesurfer_path: /Applications/freesurfer/7.3.2
project_name: devel
path_mri: '007'
skip_recon: no
afni_path: /Users/dipterix/abin
params:
  nii_t1: MRI_RAW.nii
  nii_ct: CT_RAW.nii
  template_brain: N27
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  freesurfer:
    flag: -all
    fresh_start: no
  niftyreg:
    reference: MRI_RAW.nii
    reg_type: rigid
    interp: trilinear
  ants:
    reference: MRI_RAW.nii
    reg_type: Rigid
    aff_metric: mattes
    syn_metric: mattes
  flirt:
    reference: MRI_RAW.nii
    dof: 6
    cost: mutualinfo
    search: 90
    searchcost: mutualinfo
  nipy:
    reference: MRI_RAW.nii
    clean_source: yes
    inverse_target: yes
    precenter_source: yes
    reg_type: rigid
    similarity: crl1
    interp: pv
    optimizer: powell
  afni:
    reference: MRI_RAW.nii
dcm2niix_path: /opt/homebrew/Cellar/dcm2niix/1.0.20220720/bin/dcm2niix
path_ct: '007'
skip_coregistration: no
