afni_path: /Users/dipterix/abin
dcm2niix_path: /opt/homebrew/Cellar/dcm2niix/1.0.20211006/bin/dcm2niix
freesurfer_path: /Applications/freesurfer/7.2.0
fsl_path: /usr/local/fsl
params:
  nii_t1: ''
  nii_ct: ''
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  freesurfer:
    flag: -autorecon1
    fresh_start: no
path_ct: block003
path_mri: block003
project_name: automated
skip_coregistration: no
skip_recon: no
subject_code: PAV004__block003
