afni_path: /Users/dipterix/abin
dcm2niix_path: /opt/homebrew/Cellar/dcm2niix/1.0.20220720/bin/dcm2niix
freesurfer_path: /Applications/freesurfer/7.3.2
fsl_path: /usr/local/fsl
params:
  nii_t1: DICOM_SAG_MPRAGE_20220728090416_13.nii
  nii_ct: POST_IMPLANT_CT_1_STEALTH_20220824232445_2.nii
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  freesurfer:
    flag: -autorecon1
    fresh_start: no
path_ct: post-CT
path_mri: pre-MRI
project_name: devel
skip_coregistration: no
skip_recon: no
subject_code: PAV006
