dcm2niix_path: /usr/local/bin/dcm2niix
dryrun: no
freesurfer_path: /data/R/cache_dir/freesurfer
fsl_path: /data/R/cache_dir/fsl
params:
  nii_t1: ''
  nii_ct: ''
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  freesurfer:
    steps: -all
    fresh_start: no
params_dcm2niix: ~
path_ct: localization/T01_CT_to_T01_mprageANTs.nii.gz
path_mri: 01_run1-noisywords
project_name: devel
skip_coregistration: no
skip_recon: yes
subject_code: HUP229
