afni_path: ''
dcm2niix_path: ''
freesurfer_path: ''
fsl_path: ''
params:
  nii_t1: ''
  nii_ct: ''
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  freesurfer:
    flag: -autorecon1
    fresh_start: no
path_ct: rave-imaging/DICOM
path_mri: rave-imaging/DICOM
project_name: test
skip_coregistration: no
skip_recon: no
subject_code: PAV005
