dcm2niix_path: ''
dryrun: no
freesurfer_path: /Applications/freesurfer
fsl_path: /Users/beauchamplab/fsl
params:
  nii_t1: ''
  nii_ct: ''
  dcm2niix:
    merge: Auto
    float: 'Yes'
    crop: 'No'
  freesurfer:
    steps: -all
    fresh_start: no
params_dcm2niix: ~
path_ct: Guerrero_Evangelina_Cortez/CTBRAINWITHOUTCONTRAST
path_mri: Guerrero_Evangelina_Cortez/mri
project_name: devel
skip_coregistration: no
skip_recon: yes
subject_code: YAB
