force_import: yes
import_blocks__format: Single EDF(+) file per block
import_blocks__session_block:
- NoisyWords_Run1
- NoisyWords_Run2
- NoisyWords_Run3
- NoisyWords_Run4
- NoisyWords_Run5
import_channels__electrode_file: auto
import_channels__electrodes: 14-20
import_channels__sample_rate: 1024
import_channels__unit: NA
import_setup__project_name: devel
import_setup__subject_code: PAV002
skip_validation: yes
