force_import: yes
import_blocks__format: Single BlackRock file (.nev+.nsx) per block
import_blocks__session_block: block006
import_channels__electrode_file: auto
import_channels__electrodes: 1-152
import_channels__sample_rate: 2000
import_channels__unit: NA
import_setup__project_name: devel
import_setup__subject_code: PAV005
skip_validation: yes
