force_import: yes
import_blocks__format: .mat/.h5 file per electrode per block
import_blocks__session_block: '001'
import_channels__electrode_file: auto
import_channels__electrodes: 1-233
import_channels__sample_rate: 2000
import_channels__unit: NA
import_setup__project_name: test
import_setup__subject_code: PAV005
skip_validation: yes
