kernel_table:
  Frequency:
  - 2
  - 22
  - 42
  - 62
  - 82
  - 102
  - 122
  - 142
  - 162
  - 182
  Cycles:
  - 3.0
  - 4.0
  - 4.0
  - 5.0
  - 6.0
  - 8.0
  - 9.0
  - 11.0
  - 14.0
  - 17.0
pre_downsample: 4.0
precision: float
project_name: test3
subject_code: YAB
target_sample_rate: 100.0
