kernel_table:
  Frequency:
  - 2
  - 12
  - 22
  - 32
  - 42
  - 52
  - 62
  - 72
  - 82
  - 92
  - 102
  - 112
  - 122
  - 132
  - 142
  - 152
  - 162
  - 172
  - 182
  - 192
  Cycles:
  - 2.0
  - 5.0
  - 7.0
  - 8.0
  - 9.0
  - 10.0
  - 11.0
  - 12.0
  - 13.0
  - 14.0
  - 15.0
  - 15.0
  - 16.0
  - 17.0
  - 17.0
  - 18.0
  - 18.0
  - 19.0
  - 19.0
  - 20.0
pre_downsample: 1.0
precision: double
project_name: test2
subject_code: KC
target_sample_rate: 100.0
