kernel_table:
  Frequency:
  - 2
  - 12
  - 22
  - 32
  - 42
  - 52
  - 62
  - 72
  - 82
  - 92
  - 102
  - 112
  - 122
  - 132
  - 142
  - 152
  - 162
  - 172
  - 182
  - 192
  Cycles:
  - 3.0
  - 3.0
  - 4.0
  - 4.0
  - 4.0
  - 5.0
  - 5.0
  - 6.0
  - 6.0
  - 7.0
  - 8.0
  - 9.0
  - 9.0
  - 10.0
  - 11.0
  - 13.0
  - 14.0
  - 15.0
  - 17.0
  - 19.0
pre_downsample: 4.0
precision: float
project_name: test3
subject_code: YAB
target_sample_rate: 100.0
