project_name: demo
subject_code: DemoSubject
save_pipeline: yes
epoch: default
electrodes: '14'
reference: default
intervals:
- - -1.0
  - 2.0
type: power
baseline:
- - -1
  - -0.2
baseline_method: decibel
