localization_list:
  SA.7.iEEG:
    Electrode:
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 40
    Coord_x:
    - -17.1108312
    - -20.5710404
    - -25.1941614
    - -29.3510729
    - -34.0607375
    - -38.9705837
    - -10.1139802
    Coord_y:
    - -82.6485022
    - -82.667807
    - -81.8391329
    - -81.8268976
    - -81.0324269
    - -81.0260731
    - -67.2704849
    Coord_z:
    - -52.7585458
    - -51.998144
    - -50.3395538
    - -50.3104444
    - -48.733229
    - -47.9117817
    - -51.4207272
    Label:
    - SA1
    - SA2
    - SA3
    - SA4
    - SA5
    - SA6
    - SA7
    LabelPrefix:
    - SA
    - SA
    - SA
    - SA
    - SA
    - SA
    - SA
    Dimension:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    LocationType:
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    Radius:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    SurfaceType:
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    MNI305_x:
    - -13.0930451
    - -16.7640014
    - -21.7047028
    - -26.0888651
    - -31.1177019
    - -36.3194931
    - -6.0557052
    MNI305_y:
    - -107.7737953
    - -107.5559288
    - -106.1807193
    - -106.3526072
    - -105.054147
    - -104.850798
    - -93.3022153
    MNI305_z:
    - -18.9005872
    - -18.1692794
    - -17.006746
    - -16.9648557
    - -15.8608901
    - -15.0780734
    - -25.0771294
    VertexNumber:
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    FSIndex:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1013
    FSLabel:
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - ctx-lh-lingual
    SurfaceElectrode:
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    SignalType:
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
localization_plan:
  '1':
    label: SA
    dimension: '6'
    type: iEEG
    info: ~
  '2':
    label: SA
    dimension: '1'
    type: iEEG
    info: ~
path_ct_in_t1: '{subject$freesurfer_path}/../coregistration/CT.nii.gz'
project_name: devel
subject_code: HUP229
