localization_list:
  G.64.iEEG:
    Electrode:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
    - 45
    - 46
    - 47
    - 48
    - 49
    - 50
    - 51
    - 52
    - 53
    - 54
    - 55
    - 56
    - 57
    - 58
    - 59
    - 60
    - 61
    - 62
    - 63
    - 64
    Coord_x:
    - -35.8385614
    - -32.0896902
    - -29.5293099
    - -25.5648925
    - -22.5488377
    - -18.9578076
    - -15.3607813
    - -12.6563569
    - -9.4571667
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    Coord_y:
    - -53.4100202
    - -52.3856461
    - -51.5549864
    - -50.7677049
    - -49.5787402
    - -48.684883
    - -47.7433919
    - -46.9498845
    - -46.0366505
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    Coord_z:
    - 32.973432
    - 30.0821735
    - 27.4798227
    - 23.5716078
    - 20.5668732
    - 16.9580987
    - 13.6140236
    - 10.6777916
    - 7.4838479
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    Radius:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    SurfaceType:
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    Hemisphere:
    - left
    - left
    - left
    - left
    - left
    - left
    - left
    - left
    - left
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    FSIndex:
    - 1022
    - 1171
    - 2
    - 1029
    - 2
    - 2
    - 2
    - 1025
    - 1010
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    FSLabel:
    - ctx-lh-postcentral
    - ctx-lh-S_postcentral
    - Left-Cerebral-White-Matter
    - ctx-lh-superiorparietal
    - Left-Cerebral-White-Matter
    - Left-Cerebral-White-Matter
    - Left-Cerebral-White-Matter
    - ctx-lh-precuneus
    - ctx-lh-isthmuscingulate
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    MNI305_x:
    - -38.2335161
    - -34.1895614
    - -31.4088407
    - -27.0723137
    - -23.814815
    - -19.8968122
    - -15.9878722
    - -13.0361139
    - -9.5551152
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    MNI305_y:
    - -36.1619537
    - -36.1935369
    - -36.3469444
    - -36.9972335
    - -36.9586955
    - -37.4081932
    - -37.7065903
    - -38.0218368
    - -38.3056197
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    MNI305_z:
    - 60.4184422
    - 57.2074462
    - 54.3316375
    - 50.1899917
    - 46.7839547
    - 42.8946968
    - 39.2545515
    - 36.0596132
    - 32.5717003
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    Label:
    - G1
    - G2
    - G3
    - G4
    - G5
    - G6
    - G7
    - G8
    - G9
    - G10
    - G11
    - G12
    - G13
    - G14
    - G15
    - G16
    - G17
    - G18
    - G19
    - G20
    - G21
    - G22
    - G23
    - G24
    - G25
    - G26
    - G27
    - G28
    - G29
    - G30
    - G31
    - G32
    - G33
    - G34
    - G35
    - G36
    - G37
    - G38
    - G39
    - G40
    - G41
    - G42
    - G43
    - G44
    - G45
    - G46
    - G47
    - G48
    - G49
    - G50
    - G51
    - G52
    - G53
    - G54
    - G55
    - G56
    - G57
    - G58
    - G59
    - G60
    - G61
    - G62
    - G63
    - G64
    LabelPrefix:
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    - G
    Dimension:
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    LocationType:
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    VertexNumber:
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    SurfaceElectrode:
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    SignalType:
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
  S.28.iEEG:
    Electrode:
    - 65
    - 66
    - 67
    - 68
    - 69
    - 70
    - 71
    - 72
    - 73
    - 74
    - 75
    - 76
    - 77
    - 78
    - 79
    - 80
    - 81
    - 82
    - 83
    - 84
    - 85
    - 86
    - 87
    - 88
    - 89
    - 90
    - 91
    - 92
    Coord_x:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    Coord_y:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    Coord_z:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    Radius:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    SurfaceType:
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    - pial
    Hemisphere:
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    - .na.character
    FSIndex:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    FSLabel:
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    - Unknown
    MNI305_x:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    MNI305_y:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    MNI305_z:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    Label:
    - S1
    - S2
    - S3
    - S4
    - S5
    - S6
    - S7
    - S8
    - S9
    - S10
    - S11
    - S12
    - S13
    - S14
    - S15
    - S16
    - S17
    - S18
    - S19
    - S20
    - S21
    - S22
    - S23
    - S24
    - S25
    - S26
    - S27
    - S28
    LabelPrefix:
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    - S
    Dimension:
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    - 28
    LocationType:
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    - iEEG
    VertexNumber:
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    SurfaceElectrode:
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    - no
    SignalType:
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
    - LFP
localization_plan:
  '1':
    label: ' G'
    dimension: '20'
    type: iEEG
    info: ~
  '2':
    label: ' G'
    dimension: '2'
    type: iEEG
    info: ~
  '3':
    label: ' G'
    dimension: '2'
    type: iEEG
    info: ~
  '4':
    label: ' G'
    dimension: '2'
    type: iEEG
    info: ~
  '5':
    label: ' G'
    dimension: '2'
    type: iEEG
    info: ~
path_ct_in_t1: ~
project_name: demo
subject_code: KC
