path_ct: '{subject$freesurfer_path}/../coregistration/ct_in_t1.nii.gz'
subject_code: PAV005
path_mri: ~
project_name: devel
path_transform: ~
transform_space: resampled
localization_list: ${EXTDATA-SETTINGS|localization_list|json}
localization_plan: ${EXTDATA-SETTINGS|localization_plan|json}
