analysis_electrodes: '14 '
analysis_electrodes__category: Electrode
analysis_lock: Unlocked
analysis_ranges:
  '1':
    frequency:
    - 2
    - 152
    time:
    - -0.92
    - 2
analysis_ranges__lock: Unlocked
baseline__global_baseline_choice: Per frequency, trial, and electrode
baseline__unit_of_analysis: Decibel
baseline__windows:
  '1':
    window_interval:
    - -1
    - -0.59
baseline_windows:
- - -1.0
  - -0.38
condition_groups:
  '1':
    group_name: All Conditions
    group_conditions:
    - NoCondition
electrode_category_selector: Electrode
epoch_choice: default
epoch_choice__trial_ends: 2
epoch_choice__trial_starts: -1
epoch_name: KCaOutlier
global_baseline_choice: Per frequency, trial, and electrode
loaded_electrodes: 6-7,14-15,22-23,30-31,38-39
project_name: test2
reference_name: default
subject_code: KC
trial_ends: 2
trial_starts: -1
unit_of_analysis: z-score Power
