baseline_windows:
- - -1.0
  - -0.38
unit_of_analysis: z-score Power
analysis_electrodes: '6'
baseline__windows:
  '1':
    window_interval:
    - -1
    - -0.3
trial_starts: -1
reference_name: default
project_name: demo
trial_ends: 2
analysis_electrodes__category: Electrode
electrode_category_selector: Electrode
analysis_ranges:
  '1':
    frequency:
    - 26
    - 87.5
    time:
    - 0.09
    - 1.56
  '2':
    frequency:
    - 26
    - 87.5
    time:
    - -1
    - 0
epoch_choice: KCaOutlier
epoch_name: KCaOutlier
baseline__global_baseline_choice: Per frequency, trial, and electrode
baseline__unit_of_analysis: '% Change Power'
loaded_electrodes: 6-7,14-15,22-23,30-31,38-39
subject_code: KC
analysis_ranges__lock: Lock frequency
global_baseline_choice: Per frequency, trial, and electrode
condition_groups:
  '1':
    group_name: All Conditions
    group_conditions:
    - drive_a
    - known_a
    - last_a
    - meant_a
  '2':
    group_name: Ahaha
    group_conditions:
    - AdriveVlast
    - AlastVknown
    - drive_a
epoch_choice__trial_ends: 2
epoch_choice__trial_starts: -1
analysis_lock: Unlocked
