analysis_electrodes: '15-16 '
analysis_electrodes__category: Electrode
analysis_lock: Unlocked
analysis_ranges:
  '1':
    frequency:
    - 2
    - 200
    time:
    - -1
    - 2
analysis_ranges__lock: Unlocked
baseline__global_baseline_choice: Across trial
baseline__unit_of_analysis: '% Change Power'
baseline__windows:
  '1':
    window_interval:
    - -1
    - -0.5
baseline_windows:
- - -1.0
  - -0.38
condition_groups:
  '1':
    group_name: All Conditions
    group_conditions:
    - NoCondition
electrode_category_selector: Electrode
epoch_choice: default
epoch_choice__trial_ends: 2
epoch_choice__trial_starts: -1
epoch_name: KCaOutlier
global_baseline_choice: Per frequency, trial, and electrode
loaded_electrodes: 14-25
project_name: test3
reference_name: noref
subject_code: YAB
trial_ends: 2
trial_starts: -1
unit_of_analysis: z-score Power
