analysis_electrodes: '13-16 '
analysis_electrodes__category: Electrode
analysis_ranges:
  '1':
    frequency:
    - 2
    - 152
    time:
    - -1
    - 2
analysis_ranges__lock: Unlocked
baseline__global_baseline_choice: Per frequency, trial, and electrode
baseline__unit_of_analysis: Decibel
baseline__windows:
  '1':
    window_interval:
    - -1
    - 0
condition_groups:
  '1':
    group_name: All Conditions
    group_conditions:
    - drive_a
    - known_a
    - last_a
    - meant_a
epoch_choice: auditory_onset
epoch_choice__trial_ends: 2
epoch_choice__trial_starts: -1
loaded_electrodes: 13-16,24
project_name: demo
reference_name: default
subject_code: DemoSubject
