baseline_windows:
- - -1
  - 0
unit_of_analysis: Decibel
analysis_electrodes: 1-2
trial_starts: -1
reference_name: car_withrefgrd
project_name: EMU_NoisyWords
trial_ends: 2
electrode_category_selector: Electrode
analysis_ranges:
- frequency:
  - 2
  - 200
  time:
  - -1
  - 2
epoch_name: YDP_ALL
loaded_electrodes: 1-224
global_baseline_choice: Per frequency, trial, and electrode
subject_code: YDP
condition_groups:
  '1':
    group_name: All Conditions
    group_conditions:
    - Ac0
    - Ac1
    - AcV0
    - AcV1
    - An0
    - An1
    - AnV0
    - AnV1
    - V0
    - V1
analysis_lock: Unlocked
