---
title: "RAVE-Jupyter Launcher"
output:
  html_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
# This code block sets up the engine environment
# Please do not remove me
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
build_pipeline <- raveio::configure_knitr()
# build_pipeline(make_file = "make-power_explorer.R")
if(FALSE){
  list2env(as.list(raveio::load_yaml(file.path(rstudioapi::getActiveProject(), '_pipelines/jupyterlab/settings.yaml'))), envir = globalenv())
}
```

```{rave check_jupyter_alive, language = "R", export = "jupyter_list", cue = "always"}
source('R/status.R')
jupyter_list <- jupyter_server_status(port = port, force = force)
jupyter_list$alive
```

```{rave start_jupyter, language = "R", export = "jupyter_url", cue = "always"}
if(!jupyter_list$alive){
  source('R/status.R')
  rpymat::jupyter_launch(
    workdir = raveio::raveio_getopt("data_dir"),
    host = host,
    port = port, 
    open_browser = FALSE, 
    async = TRUE, 
    token = token,
    use_rs = FALSE
  )
  # change settings back to force = FALSE
  settings <- raveio::load_yaml("settings.yaml")
  settings$force <- FALSE
  raveio::save_yaml(settings, "settings.yaml")
  
  # wait the server to launch
  Sys.sleep(3)
  jupyter_list <- jupyter_server_status(port = port, force = FALSE)
}
instance <- jupyter_list$instances[
  jupyter_list$instances$port == port
]
jupyter_url <- sprintf("http://%s:%s/jupyter/lab?token=%s",
        instance$host, instance$port, instance$token)
jupyter_url
```

## Build, Visualize, & Run


```{r build, echo=FALSE, results='hide'}
build_pipeline(make_file = "make-jupyterlab.R")
```

```{r execute}
Sys.setenv("RAVE_PIPELINE" = normalizePath("."))
raveio::pipeline_run(type = "vanilla")
raveio::pipeline_progress(method = 'details')
```

```{r visualize, echo=FALSE}
Sys.setenv("RAVE_PIPELINE" = normalizePath("."))
raveio::pipeline_visualize()
```








